fix use only healthcheck

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,31 +17,31 @@ jobs:
         # timeout-minutes: 4
         run: |
           # Start container
-          docker compose -f services/mc-server.yaml up &
+          docker compose -f services/mc-server.yaml up --wait
 
-          # Wait for the container to be up
-          while ! docker inspect services-mc-1 &>/dev/null; do
-            sleep 1
-          done
-          # Start timer
-          start_time=$(date +%s)
-          # Start check exit code when time reached
-          # Convert min to sec
-          min=4 # Set time here
-          wait_sec=$((min*60))
-          while true; do
-            exitCode=$(docker inspect -f "{{.State.ExitCode}}" services-mc-1)
-            health=$(docker inspect -f "{{.State.Health.Status}}" services-mc-1)
-            current_time=$(date +%s) # Get current time
-            elapsed_time=$((current_time - start_time)) # Calc time
-            if (( elapsed_time >= wait_sec && exitCode == 0 )); then
-              exit 0
-            elif (( exitCode == 1 && "$health" == "unhealthy" )); then
-              break
-            fi
-            sleep 1
-          done
-          exit 1
+          # # Wait for the container to be up
+          # while ! docker inspect services-mc-1 &>/dev/null; do
+          #   sleep 1
+          # done
+          # # Start timer
+          # start_time=$(date +%s)
+          # # Start check exit code when time reached
+          # # Convert min to sec
+          # min=4 # Set time here
+          # wait_sec=$((min*60))
+          # while true; do
+          #   exitCode=$(docker inspect -f "{{.State.ExitCode}}" services-mc-1)
+          #   health=$(docker inspect -f "{{.State.Health.Status}}" services-mc-1)
+          #   current_time=$(date +%s) # Get current time
+          #   elapsed_time=$((current_time - start_time)) # Calc time
+          #   if (( elapsed_time >= wait_sec && exitCode == 0 && "$health" == "healthy" )); then
+          #     exit 0
+          #   elif (( exitCode == 1 && "$health" == "unhealthy" )); then
+          #     break
+          #   fi
+          #   sleep 1
+          # done
+          # exit 1
 
           # while true
           # do
