fix 13

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,14 +29,14 @@ jobs:
           while true; do
             # Convert min to sec
             min=4 # Set time here
-            wait_sec=$min*60
-            output=$(docker inspect -f "{{.State.ExitCode}}" services-mc-1)
+            wait_sec=$(min*60)
+            exitCode=$(docker inspect -f "{{.State.ExitCode}}" services-mc-1)
             current_time=$(date +%s) # Get current time
             elapsed_time=$((current_time - start_time)) # Calc time
-            if (( elapsed_time >= $wait_sec && output == 0 )); then
+            if (( elapsed_time >= wait_sec && exitCode == 0 )); then
               exit 0
               break
-            else
+            else (( exitCode == 1 )); then
               break
             fi
             sleep 1
@@ -51,14 +51,14 @@ jobs:
           # done
 
           # Check Health
-      - name: Get container health
-        run: |
-          output=$(docker inspect -f "{{.State.Health.Status}}" services-mc-1)
-          if [[ "$output" == "healthy" ]]; then
-            echo "Exit code = 0" >> $GITHUB_OUTPUT
-            exit 0
-          else
-            echo "Exit code = 1" >> $GITHUB_OUTPUT
-            exit 1
-          fi
+      # - name: Get container health
+      #   run: |
+      #     output=$(docker inspect -f "{{.State.Health.Status}}" services-mc-1)
+      #     if [[ "$output" == "healthy" ]]; then
+      #       echo "Exit code = 0" >> $GITHUB_OUTPUT
+      #       exit 0
+      #     else
+      #       echo "Exit code = 1" >> $GITHUB_OUTPUT
+      #       exit 1
+      #     fi
 
